### PR TITLE
Implementation of Brendel & Bethge attack

### PR DESCRIPTION
**Pull request by wielandbrendel**
Implementation is almost finished.

- [x] Fix infinite loop in L0
- [x] Performance test of L2 version
- [x] Performance test of L0 version
- [x] Performance test of L1 version
- [x] Performance test of Linf version
- [x] Remove print statement
- [x] Add doc note that highlights and explains difference of lr adaptation to paper implementation

### CODE REVIEW

**Comment by wielandbrendel** [comment]
The attack is almost ready now, I only need to remove the print statement and resolve the existing conflicts. @jonasrauber Could you take a look whether there is anything else?

**Comment by wielandbrendel** [comment]
@jonasrauber From my side everything is done. Would be great if we could merge beginning of next week :).

**Comment by jonasrauber** [comment]
Are you sure the tests are the way you want them to be? You are always checking the L2 norm and you only checking that at least one sample is adversarial (you can be stricter if you know the attack returns only adversarials; `== 0`).

Regarding the actual attack: I am sure you have tested it and I am happy to just merge it.

Regarding the `PrecomputedSamplesAttack`: Let's talk about it.

**Comment by wielandbrendel** [comment]
@jonasrauber Good catch! I fixed the tests now.

Lets talk about the `PrecomputedSamplesAttack` tomorrow.

**Comment by jonasrauber** [comment]
As discussed, I will merge it now and then make some follow-up changes to the `PrecomputedSamplesAttack` afterwards

**Pull request merged**
